"""initial_schema

Revision ID: 61c84e453f9c
Revises:
Create Date: 2026-05-16 23:13:12.655799

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "61c84e453f9c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
