[mypy]
python_version = 3.12
strict = True
plugins = pydantic.mypy
exclude = (alembic/versions/|\.venv/)
warn_unreachable = True
warn_unused_ignores = True
disallow_untyped_decorators = False

[mypy-tests.*]
disallow_untyped_defs = False

[mypy-passlib.*]
ignore_missing_imports = True
